### ISSUE TITLE
LNbits >=0.12.6 no longer supports opening the links from QR codes directly in browser

### ISSUE THREAD

**Issue by suurt8ll** [lnbits/withdraw#36]
### Versions ###
LNbits: 0.12.8
LNURLw: 0.1.9

### Description ###
This commit seems to be the one causing this: https://github.com/lnbits/lnbits/commit/25661ddff5b3fcaf00107f050c7b1f7db2af2687. It was included in version 0.12.6. Now user gets the following error when scanning the QR code with simple QR scanner (not with the wallet app) and visiting the site provided:

![image](https://github.com/lnbits/withdraw/assets/46417608/6bfa1a78-4166-40e3-bf02-5c0cb9ea75cd)

I don't know about NFC but QR codes currently encode a link following this format:  https://demo.lnbits.com/?lightning=LNURL... QR codes encoding only the LNURL work fine in wallets.

### Possible fixes ###

- **"LNbits bonus:"** section from README should be removed or include a warning about recent versions not supporting it anymore.
- Encode only the LNURL address into QR codes without the link to the LNbits site.

**Comment by dni** [comment]
https://github.com/lnbits/lnbits/pull/2625
